/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gerenciaPetsTelas;

import GerenciaPetsDados.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ANDRESSA
 */
public class Pedidos extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
         conexao = ModuloConexao.conectar();
          pedidos_producao();
          pedidos_empacotando();
    }
    
   private void pedidos_producao(){
    String sql = "select tipo as Tipo, situacao as Situação, tipo_alimento as Tipo_de_alimento,"
            + " quantidade_pacotes as Quantidade_de_pacotes from dbpets.tbos where situacao = 'Produção'"; 
    try{
        pst = conexao.prepareStatement(sql);
        rs = pst.executeQuery();
        
        tblProducao.setModel(DbUtils.resultSetToTableModel(rs));
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,"Ocorreu um erro ao carregar os dados de produção.");
    }
}
   private void pedidos_empacotando(){
    String sql = "select tipo as Tipo, situacao as Situação, tipo_alimento as Tipo_de_alimento,"
            + " quantidade_pacotes as Quantidade_de_pacotes from dbpets.tbos where situacao = 'Empacotando'"; 
    try{
        pst = conexao.prepareStatement(sql);
        rs = pst.executeQuery();
        
        tblEmpacotando.setModel(DbUtils.resultSetToTableModel(rs));
    } catch(Exception e){
        JOptionPane.showMessageDialog(null,"Ocorreu um erro ao carregar os dados de empacotamento.");
    }
}
   


 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProducao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducao = new javax.swing.JTable();
        lblEmpacotando = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpacotando = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 800));

        lblProducao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProducao.setText("Produção");

        tblProducao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProducao);

        lblEmpacotando.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmpacotando.setText("Empacotando");

        tblEmpacotando.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEmpacotando);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANDRESSA\\Documents\\GerenciaPets\\prjPets\\icones\\fechar (1).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblProducao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblEmpacotando)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblProducao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblEmpacotando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setBounds(0, 0, 635, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pedidos.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmpacotando;
    private javax.swing.JLabel lblProducao;
    private javax.swing.JTable tblEmpacotando;
    private javax.swing.JTable tblProducao;
    // End of variables declaration//GEN-END:variables
}
